# Result Backend Configuration for YADTQ

# PostgreSQL backend configuration
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: task_results
  ssl_mode: disable
  pool_size: 10
  connection_timeout: 30
  # Task-specific table settings
  table_name: task_results
  schema: public

# MongoDB backend configuration
mongodb:
  uri: mongodb://localhost:27017/
  database: task_results
  collection: results
  connect_timeout: 5000
  # Additional settings for distributed operation
  write_concern: 1
  read_preference: primaryPreferred
  max_pool_size: 100
  retry_writes: true

# File system backend configuration
file:
  path: /tmp/task_results
  encoding: utf-8
  # Added settings for better file management
  max_file_size: 100MB
  rotation_interval: 24h
  cleanup_interval: 168h  # 7 days

# General settings
settings:
  default_backend: mongodb  # Choose your preferred backend
  task_result_ttl: 86400   # How long to keep results (in seconds)
  
  # Task status tracking
  status_types:
    - queued
    - processing
    - success
    - failed

  # Result structure
  result_schema:
    task_id: string
    status: string
    result: any
    error: string
    created_at: timestamp
    updated_at: timestamp
    worker_id: string